### ISSUE TITLE
Compilation errors with `dim==1`

### ISSUE THREAD

**Issue by mschreter** [kronbichler/adaflo#84]
Currently, adaflo does not compile for `dim==1` with current deal.II master due to the changes made in https://github.com/dealii/dealii/pull/16770

- One issue is related to a call of `FEEvaluation::get_divergence()` for `dim==1`  here https://github.com/kronbichler/adaflo/blob/6329eeec998ce7f4d527f4fed96b9043e9ca2106/source/navier_stokes_matrix.cc#L954 which is disabled by https://github.com/dealii/dealii/pull/16770.
- Another issue is related to the fact that we introduced utility functions for `dim==1, n_components==dim` which converts the 
`gradient_type = Tensor<1,dim,VectorizedArray<double>>` obtained from the FEEvaluation access to `Tensor<2,dim,VectorizedArray<double>>`, to obtain the same types as for `dim>1` via https://github.com/kronbichler/adaflo/blob/6329eeec998ce7f4d527f4fed96b9043e9ca2106/source/navier_stokes_matrix.cc#L703-L704 and https://github.com/kronbichler/adaflo/blob/6329eeec998ce7f4d527f4fed96b9043e9ca2106/include/adaflo/util.h#L146-L179. Our motivation for this was to straightforward loop over the components and make component-wise modifications. However, https://github.com/dealii/dealii/pull/16770 requires to submit the original `gradient_type`, which makes e.g.  https://github.com/kronbichler/adaflo/blob/6329eeec998ce7f4d527f4fed96b9043e9ca2106/source/navier_stokes_matrix.cc#L891 invalid.

My workaround for the described cases looks currently as follows
https://github.com/kronbichler/adaflo/blob/2acdbf6b2096459ee073fea9be695d91f1b242bd/source/navier_stokes_matrix.cc#L982-L986
https://github.com/kronbichler/adaflo/blob/2acdbf6b2096459ee073fea9be695d91f1b242bd/source/navier_stokes_matrix.cc#L916-L919

@kronbichler do you have any suggestions how to implement such special cases with `dim==1` in the future? 
I want to make sure that we are on the same page here. Just as a remark: https://github.com/dealii/dealii/pull/16776 requires even more changes.

**Comment by kronbichler** [comment]
I see the point; it seems that the tests in deal.II are less comprehensive than I thought they are, so anyway this indicates we should work towards additional 1D tests. My apologies for not testing here, this is an oversight.
In my later PR https://github.com/dealii/dealii/pull/16776, I indeed enabled `get_divergence` for 1D due to the benefits. I think we should aim to avoid the `constexpr` cases as you introduced them here, and I think we can get all the features into the now single call function. I think we should start from the latter PR because, as you state correctly, it again changes some of the edge cases. We should discuss it there and try to edge out possible incompatibilities for the 1D case. Essentially, the problem there can be traced back to the missing compatibility layer we had for 1D/vector-valued variables. I added two functions now to https://github.com/dealii/dealii/pull/16776, can you check again?

**Comment by mschreter** [comment]
@kronbichler It looks now much better, using https://github.com/dealii/dealii/pull/16776 adaflo (and MeltPoolDG) compiles now without any compatibility changes :-). This should be a good sign since we consider many 1D cases. Thank you very much for the quick fix.
